name       : xpra
version    : 4.2.3
release    : 1
source     :
    - https://github.com/Xpra-org/xpra/archive/refs/tags/v4.2.3.tar.gz : 69759c716d0dd50dba7c816f8a4c4afdfee4553d1aa8bd5104874e95a4ffd207
homepage   : https://xpra.org
license    : GPL-2.0-or-later
component  : desktop
summary    : multi-platform screen and application forwarding system
description: |
    Xpra is a multi platform persistent remote display server and client for forwarding applications and desktop screens. Also known as 'screen for X11'.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - cython
    - pandoc
rundeps    :
    - python-evdev
    - python-netifaces
    - python-paramiko
    - python-pillow
    - qrencode
    - xorg-server-xvfb
setup      : |
    %apply_patches
build      : |
    %python3_setup --without-Xdummy --without-Xdummy_wrapper
install    : |
    %python3_install
