name       : xpra
version    : 4.3.2
release    : 4
source     :
    - https://github.com/Xpra-org/xpra/archive/refs/tags/v4.3.2.tar.gz : 1e548b8d20c243fba40692abb0aa2759e3bd3f2d3b6b51a160f82746cdf1d782
homepage   : https://xpra.org
license    : GPL-2.0-or-later
component  : desktop
summary    : multi-platform screen and application forwarding system
description: |
    Xpra is a multi platform persistent remote display server and client for forwarding applications and desktop screens. Also known as 'screen for X11'.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xres)
    - cython
    - pandoc
rundeps    :
    - python-evdev
    - python-netifaces
    - python-paramiko
    - python-pillow
    - qrencode
    - xorg-server-xvfb
setup      : |
    mv -v $workdir/fs/etc/sysconfig/xpra $workdir/fs/etc/sysconfig/xpra.env
    %apply_patches
build      : |
    %python3_setup --without-Xdummy --without-Xdummy_wrapper
install    : |
    %python3_install
